### ISSUE TITLE
Top bar display transparent when reloading scrolled page

### ISSUE THREAD

**Issue by trando95** [chaineco/blockcare#109]
![Image](https://github.com/user-attachments/assets/a13d78ab-fbf1-4ba2-b7fb-9adc63b77ca4)

**Comment by trando95** [comment]
![Image](https://github.com/user-attachments/assets/18018eff-6b98-4f95-b938-79d56425e59c)

**Comment by thanhnp2k** [comment]
commited:
https://github.com/chaineco/blockcare/commit/3f346fd2663a8d941b7d8bd3a75d5abbf9272556
