### ISSUE TITLE
Set default Zoom view mode on report charts. Save chart state when switching between report types

### ISSUE THREAD

**Issue by thanhnp2k** [chaineco/blockcare#118]
- [x] Adjust default Zoom option on Domain chart
- [x] Adjust default Zoom option on Treasury Spending chart (Apply for all Treasury tyep report)

**Comment by trando95** [comment]
Resolved on:
https://github.com/chaineco/blockcare/commit/3bcde2569a79b6419155374b3d7d722fc1f51583
