### ISSUE TITLE
Add Unaccounted and Total data to Monthly (Yearly) detail report

### ISSUE THREAD

**Issue by thanhnp2k** [chaineco/blockcare#138]

**Comment by thanhnp2k** [comment]
https://github.com/chaineco/blockcare/commit/953bd62d9be3797f6ee208ed3dd06152278ef7cd
Added to Year/Month detail report
Hanlder usd rate for monthly

**Comment by trando95** [comment]
Resolved on:
https://github.com/chaineco/blockcare/commit/5464510f25336899a6e203717496d79bd97b81ee
https://github.com/chaineco/blockcare/commit/f3bd22c7b9831265087d8af9590cd8940c0f7d32
https://github.com/chaineco/blockcare/commit/2768063ed810a0fbc016282bf4ec820ac2490e65
https://github.com/chaineco/blockcare/commit/fbf567b6d125244128de937e318ac7af4b354e78
https://github.com/chaineco/blockcare/commit/fe5738d149b1f4d595f809685c82aeab1f9b438a
