### ISSUE TITLE
Create page to display current treasury transaction status

### ISSUE THREAD

**Issue by chaineco** [chaineco/blockcare#56]
display mempool treasury transaction status that is not yet confirmed in a block
even better if can show the real time voting information as well

**Comment by thanhnp2k** [comment]
Being discussed:
Currently, unconfirmed treasury transactions are displayed on the mempool page. Is it necessary to create a new page to display them?

**Comment by thanhnp2k** [comment]
No spending treasury tx to confirm. According to the source code, it seems that transactions that have not yet completed voting are still fully displayed

**Comment by thanhnp2k** [comment]
https://github.com/chaineco/blockcare/assets/149697594/eff6ac49-e941-4722-9b4d-654a2ab3f688

**Comment by thanhnp2k** [comment]
Show unconfirmed transactions (in the mempool) on all other pages that show transactions. Close this issue and create another issue to implement.
