### ISSUE TITLE
Unify the sortable for data tables on the general report and on the detail report

### ISSUE THREAD

**Issue by thanhnp2k** [chaineco/blockcare#8]
Most columns on existing tables are sortable and sorting has been added.
However, there are still some columns in some tables that have not been sorted yet.
Review all tables and re-unify the sortable columns

**Comment by thanhnp2k** [comment]
- Handler sortable of balance in treasury table
- Handler sortable in domain report

**Comment by chaineco** [comment]
Fix error on sortable of Author Name on Author Report (Not reflected on the arrangement icon)

**Comment by chaineco** [comment]
Set the default sorting value in the proposal data table in details by month and year
